TA/TA/Controllers/ClockingController.cs
using System.Web.Mvc;
using TA.Models;

namespace TA.Controllers
{
    [Authorize(Roles = "NurseryWorker")]
    public class ClockingController : Controller
    {
        // GET: Clocking
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Start()
        {
            Clocking.Action(Clocking.ClockStatus.Start);
            return Json(new { success = "true" }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult LunchStart()
        {
            Clocking.Action(Clocking.ClockStatus.LunchStart);
            return Json(new { success = "true" }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult LunchEnd()
        {
            Clocking.Action(Clocking.ClockStatus.LunchEnd);
            return Json(new { success = "true" }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult End()
        {
            Clocking.Action(Clocking.ClockStatus.End);
            return Json(new { success = "true" }, JsonRequestBehavior.AllowGet);
        }
    }
}

TA/TA/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity;
using TA.Models;

namespace TA.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult List()
        {
            ApplicationUserManager userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            IQueryable<ApplicationUser> users = userManager.Users;
            BootGrid gridData = new BootGrid(-1, users.Count(), users.ToList(), users.Count());
            return Json(gridData);
        }
    }
}

TA/TA/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("TA", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Clock In", "Index", "Clocking")</li>
                    <li>@Html.ActionLink("Users", "Index", "User")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div id="siteSuccess" class="alert alert-success collapse" role="alert" style="display:none">
        <button type="button" class="close" data-hide="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <div id="siteSuccessMessage"></div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 
            LiTE Software Solutions ltd</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/Plugins")
    @Scripts.Render("~/bundles/TA")
    @RenderSection("scripts", required: false)
</body>
</html>